### ISSUE TITLE
Can't access Internet from inside container

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/docker#1]
Not sure when this happened, but I can't access the Internet from inside the container unless I add `--net=host`, e.g.

    docker run --net=host  -t -i fenicsproject/dev:latest

README files need to be updated.

**Comment by lzlarryli** [comment]
It seems to be working on my machines now. Is it still an issue?

**Comment by jhale** [comment]
Confident that this is an upstream bug in docker, so going to close. Reopen if still an issue.
