### ISSUE TITLE
Bump PETSc and SLEPc to 3.6.0

### ISSUE THREAD

**Issue by jhale** [FEniCS/docker#2]
Waiting on tags/tarballs for petsc4py and slepc4py from Lisandro.

**Comment by garth-wells** [comment]
Looks like tarballs are ready.

**Comment by jhale** [comment]
Right, but it broke compiling dolfin-1.5.0 so I had to move back for now...

Overall I'm not very happy with the current workflow, it needs rethinking.
I really don't like how the image gets rebuilt every time there is a push
to FEniCS/Docker on github, for example. I will have a think about it, but
pretty busy at the moment so might be a week or so before I find an answer.

Jack Hale

**Comment by garth-wells** [comment]
FEniCS 1.6 will support PETSc 3.6.

Is https://quay.io/ the solution?

**Comment by jhale** [comment]
Quay.io is probably the solution. I suspect the proper solution is to have
two branches of FEniCs/Docker and then migrate tested and stable images
across using tags. But it needs more thought on my end.

Jack Hale

**Comment by garth-wells** [comment]
FEniCS 1.6 is out, so I think we can address this issue now.

**Comment by jhale** [comment]
Great I will try and bump up the builds today (in USA this week).

Jack Hale

**Comment by jhale** [comment]
Made changes, lets see how it goes on Dockerhub builds.

Jack Hale

**Comment by jhale** [comment]
Ready, I even tweeted it to #fenicsnews #behindthetimes.

Jack Hale

**Comment by jhale** [comment]
Done.
