### ISSUE TITLE
Rename the repository

### ISSUE THREAD

**Issue by lzlarryli** [FEniCS/docker#4]
I think the repository should be renamed to something like "fenics_docker" or something. The current name looks as if we forked docker.

**Comment by jhale** [comment]
Sounds good to me.

**Comment by garth-wells** [comment]
On 1 August 2015 at 03:31, Jack S. Hale <notifications@github.com> wrote:

> Sounds good to me.
> On 31 Jul 2015 16:19, "LIZAO LI" <notifications@github.com> wrote:
>
> > I think the repository should be renamed to something like
> "fenics_docker"
> > or something. The current name looks as if we forked docker.
> >
>

Looks strange when part of a project, '/fenicsproject/fenics_docker'.

In any case, I prefer fenics-docker to fenics_docker. I'm tired of
underscores ;).

Garth

**Comment by jhale** [comment]
Not a big fan of underscores either, fenics-docker is fine.

**Comment by lzlarryli** [comment]
I agree. Too much work to change with not much to gain. Keeping fenics/docker is fine.
